### ISSUE TITLE
Some effects aren't disabled/reverted when sm_chaos_enabled is set to zero

### ISSUE THREAD

**Issue by Tiagoquix** [Mikusch/ChaosModTF2#21]
Hello!

There is an effect in Chaos Mod that leaves health and ammo packs as static props.

![image](https://github.com/Mikusch/ChaosModTF2/assets/30274161/607eb3d8-36a5-4ae9-8658-7ba72141dfa6)

Likewise, there is an effect that randomly removes entities from the map.

From what I've seen in the plugin code, the effects are disabled and reverted when setting the `enabled` ConVar is set to zero, but this doesn't seem to apply to all effects (like, for example, the ones I mentioned above).

Would it be possible to automatically revert them without restarting the round (mp_restartgame)? If not, perhaps it would be better to restart the round when manually disabling Chaos Mod after such effects have been activated?

For better context, I play on a server where this plugin is installed, but the admins purposely choose to leave the plugin disabled by default and only activate it when they want.

**Comment by Mikusch** [comment]
Restoring the previous state is very tricky due to all the entities differing from each other. It is more than possible to restart the round when sm_chaos_enabled is set to 0, though. Would that suffice?
