### ISSUE TITLE
it seems eternal screaming causes the server to crash

### ISSUE THREAD

**Issue by StShAzzy** [Mikusch/ChaosModTF2#3]
it just goes to the edict limit and  then the server crashes because there are no free edicts.

a crash report relating to that: https://crash.limetech.org/ruhen7qngibu

sourcemod version: 1.12.0.6948 (linux)

btw, these are the 2 biggest entities 

L 02/23/2023 - 19:00:43: (54.22%) 1111 (it's unnamed, probably was initializing so it didn't get a name assigned to it)
L 02/23/2023 - 19:00:43: (17.86%) 366	instanced_scripted_scene (controls facial expresions)

**Comment by Mikusch** [comment]
Not reproducible for me. Even on a full server the instanced_scripted_scene count does not exceed 50 during the effect.

The callstack shows you have an extension `sigsegv-optimize-only` hooking into `AcceptInput`. You should try disabling that.

**Comment by StShAzzy** [comment]
i'll look into it and report if it changes anything.

**Comment by StShAzzy** [comment]
you are right, it's an issue with sigsegv-optimize-only, i'll look into a fix for that locally
